[package]
name = "now-fetch"
version = "0.1.0"
authors = ["Martin Disch <martindisch@gmail.com>"]
edition = "2018"

[dependencies]
eyre = "0.6.5"
serde = { version = "1.0.125", features = [ "derive" ] }
quick-xml = { version = "0.22.0", features = [ "serialize" ] }
csv = "1.1.6"
